---
doublestar: true
include:
  - "**/*.yml"
  - "**/*.yaml"
exclude:
  - ".venv/**"
  - "node_modules/**"
  - ".git/**"
  - "*bazel*/**"
  - '*cahce*/**'
gitignore_excludes: true
formatter:
  type: basic
  indent: 2
  include_document_start: true
  pad_line_comments: 2
  eof_newline: true
  max_line_length: 72
