
[tool.ruff]
line-length = 79

[tool.ruff.lint]
# https://docs.astral.sh/ruff/rules/
select = [
    "ERA",      # eradicate (ERA)
    "FAST",     # FastAPI (FAST)
    "YTT",      # flake8-2020 (YTT)
    "ANN",      # flake8-annotations (ANN)
    "ASYNC",    # flake8-async (ASYNC)
    "S",        # flake8-bandit (S)
    "BLE",      # flake8-blind-except (BLE)
    "FBT",      # flake8-boolean-trap (FBT)
    "B",        # flake8-bugbear (B)
    "A",        # flake8-builtins (A)
    "COM",      # flake8-commas (COM)
    "C4",       # flake8-comprehensions (C4)
    "DTZ",      # flake8-datetimez (DTZ)
    "EM",       # flake8-errmsg (EM)
    "EXE",      # flake8-executable (EXE)
    "ISC",      # flake8-implicit-str-concat (ISC)
    "ICN",      # flake-8-import-conventions (ICN)
    "LOG",      # flake8-logging (LOG)
    "G",        # flake8-logging-format (G)
    "PIE",      # flake8-pie (PIE)
    "T20",      # flake8-print (T20)
    "PYI",      # flake8-pyi (PYI)
    "PT",       # flake8-pytest-style (PT)
    "Q",        # flake8-quotes (Q)
    "RSE",      # flake8-raise
    "RET",      # flake8-return
    "SIM",      # flake8-simplify (SIM)
    "SLOT",     # flake8-slots (SLOT)
    "TID",      # flake8-tidy-imports (TID)
    "TC",       # flake8-type-checking (TC)
    "ARG",      # flake8-unused-arguments
    "PTH",      # flake8-use-pathlib
    "FLY",      # flynt (FLY)
    "I",        # isort (I)
    "C90",      # mccabe (C90)
    "NPY",      # NumPy-specific rules (NPY)
    "PD",       # pandas-vet (PD)
    "N",        # pep8-naming (N)
    "PERF",     # Perflint (PERF)
    "E"

]