package(default_visibility = ["//visibility:public"])

filegroup(
    name = "libs",
    srcs = [
        "//lib/config_lib",
        "//lib/file_lib",
        "//lib/logger_lib",
        "//lib/test_lib",
    ],
)
